### PR TITLE
fix: 修复 xss 攻击漏洞 #796

### PR DESCRIPTION
**Pull request by yuri0528**

### CODE REVIEW

**Comment by tencentblueking-adm** [comment]
[CLA assistant check](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-user?pullRequest=800) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-user?pullRequest=800) before we can accept your contribution.<br/><hr/>**v_yutyi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-user?pullRequest=800) it.</sub>

**Comment by wklken** [comment]
稍微hold一段时间, 跟随下一个小版本走测试/出包流程

**Comment by Canway-shiisa** [comment]
这里还存在一种情况没有检验：已存在用户进行编辑没有做校验

**Comment by yuri0528** [comment]
> 这里还存在于一种情况没有检验：已存在于用户进行编辑没有做校检验

已经存在的用户不去重新编辑的话就没有进行校验，我把这个问题尽快处理一下

**Pull request merged**
